# Step 1: Use official Golang image as base
FROM golang:1.25-alpine


# Step 2: Set working directory inside container
WORKDIR /app

# Step 3: Copy go.mod and go.sum first
COPY go.mod go.sum ./

# Step 4: Download dependencies
RUN go mod download

# Step 5: Copy the rest of the code
COPY . .

# Step 6: Build the Go app
RUN go build -o main .

# Step 7: Expose port 8080
EXPOSE 8080

# Step 8: Run the app
CMD ["./main"]
